[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/Alex-lsky/ACL4SSR/main/XiaoMi.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🧭 组网,https://raw.githubusercontent.com/Alex-lsky/ACL4SSR/main/MyNetwork.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/Alex-lsky/ACL4SSR/main/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
ruleset=🤖 AI,https://raw.githubusercontent.com/Alex-lsky/ACL4SSR/main/OpenAI.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 公司地址,https://raw.githubusercontent.com/Alex-lsky/ACL4SSR/main/ChinaOnly.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🌏 东南亚节点`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🌏 东南亚节点`[]🇭🇰 香港节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🌏 东南亚节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇨🇳 大陆节点`[]🚀 手动切换
custom_proxy_group=🧭 组网`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=🎯 公司地址`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇨🇳 大陆节点`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🌏 东南亚节点`[]🇺🇲 美国节点`[]🌎 美洲节点`[]🇪🇺 欧洲节点`[]🕌 中东节点`[]🦘 大洋洲节点`[]🌍 非洲节点`[]🗺️ 其他地区`[]🚀 手动切换
custom_proxy_group=🇨🇳 大陆节点`url-test`^(?!.*(?!🇨🇳)[🇦-🇿]{2}).*(中国|大陆|回国|国内|内地|China|china|移动|联通|电信|广电|北京|上海|广州|深圳|杭州|南京|成都|武汉|西安|天津|重庆|青岛|大连|福州|厦门|苏州|无锡|宁波|长沙|郑州|济南|合肥|南昌|昆明|贵阳|南宁|哈尔滨|沈阳|长春|石家庄|太原|兰州|乌鲁木齐|呼和浩特|西宁|银川|拉萨)`http://connectivitycheck.platform.hicloud.com/generate_204`30,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|Singapore)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🌏 东南亚节点`url-test`(台湾|台|新北|彰化|TW|Taiwan|澳门|MO|Macau|Macao|韩国|韩|韓國|首尔|KR|Korea|KOR|泰国|曼谷|TH|Thailand|Bangkok|越南|河内|胡志明|VN|Vietnam|Hanoi|HCMC|马来西亚|马来|吉隆坡|MY|Malaysia|印尼|雅加达|ID|Indonesia|Jakarta|菲律宾|马尼拉|PH|Philippines|Manila|印度|孟买|India|Mumbai|缅甸|Myanmar|柬埔寨|Cambodia|老挝|Laos|蒙古|Mongolia|巴基斯坦|Pakistan|孟加拉|Bangladesh|尼泊尔|Nepal|斯里兰卡|Sri Lanka)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`https://cp.cloudflare.com/generate_204`300,,150
custom_proxy_group=🌎 美洲节点`url-test`(加拿大|多伦多|温哥华|CA|Canada|Toronto|Vancouver|巴西|圣保罗|BR|Brazil|Sao Paulo|墨西哥|MX|Mexico|阿根廷|AR|Argentina|智利|CL|Chile|哥伦比亚|Colombia|秘鲁|Peru|乌拉圭|Uruguay|巴拿马|Panama|哥斯达黎加|Costa Rica|委内瑞拉|Venezuela|厄瓜多尔|Ecuador|波多黎各|Puerto Rico)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇪🇺 欧洲节点`url-test`(英国|伦敦|UK|GB|United Kingdom|London|德国|法兰克福|DE|Germany|Frankfurt|法国|巴黎|FR|France|Paris|荷兰|阿姆斯特丹|NL|Netherlands|Amsterdam|瑞士|苏黎世|CH|Switzerland|Zurich|瑞典|斯德哥尔摩|SE|Sweden|Stockholm|意大利|米兰|IT|Italy|Milan|Milano|西班牙|马德里|ES|Spain|Madrid|俄罗斯|莫斯科|RU|Russia|Moscow|土耳其|伊斯坦布尔|TR|Turkey|Istanbul|波兰|华沙|Poland|Warsaw|芬兰|赫尔辛基|FI|Finland|丹麦|哥本哈根|DK|Denmark|挪威|奥斯陆|Norway|Oslo|爱尔兰|都柏林|Ireland|Dublin|葡萄牙|里斯本|Portugal|Lisbon|奥地利|维也纳|Austria|Vienna|比利时|布鲁塞尔|Belgium|Brussels|捷克|布拉格|Czech|Prague|希腊|雅典|Greece|Athens|匈牙利|布达佩斯|Hungary|Budapest|乌克兰|基辅|Ukraine|Kyiv|罗马尼亚|布加勒斯特|Romania|Bucharest|保加利亚|索菲亚|Bulgaria|Sofia|塞尔维亚|贝尔格莱德|Serbia|Belgrade|克罗地亚|Croatia|立陶宛|Lithuania|爱沙尼亚|Estonia|拉脱维亚|Latvia|斯洛伐克|Slovakia|斯洛文尼亚|Slovenia)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🕌 中东节点`url-test`(阿联酋|迪拜|UAE|Dubai|沙特|Saudi|阿曼|Oman|卡塔尔|Qatar|巴林|Bahrain|科威特|Kuwait|以色列|Israel|伊朗|Iran|伊拉克|Iraq|约旦|Jordan|黎巴嫩|Lebanon|叙利亚|Syria)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🦘 大洋洲节点`url-test`(澳洲|澳大利亚|悉尼|墨尔本|AU|Australia|Sydney|Melbourne|新西兰|奥克兰|NZ|New Zealand|Auckland)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🌍 非洲节点`url-test`(南非|开普敦|约堡|约翰内斯堡|South Africa|ZA|埃及|开罗|Egypt|EG|肯尼亚|内罗毕|Kenya|KE|埃塞俄比亚|Ethiopia|ET|毛里求斯|Mauritius|MU|尼日利亚|拉各斯|Nigeria|Lagos|摩洛哥|Morocco|卡萨布兰卡|Casablanca)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🗺️ 其他地区`url-test`^(?!.*(?:🇭🇰|🇨🇳|🇸🇬|🇯🇵|🌏|🇺🇲|🌎|🇪🇺|🕌|🦘|🌍|🇹🇼|🇲🇴|🇰🇷|🇨🇦|🇬🇧|🇩🇪|🇫🇷|🇳🇱|🇨🇭|🇸🇪|🇮🇹|🇪🇸|🇷🇺|🇹🇷|🇦🇪|🇦🇺|🇮🇳|🇹🇭|🇻🇳|🇲🇾|🇮🇩|🇵🇭|🇧🇷)).*`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

url_test=https://cp.cloudflare.com/generate_204
url_test_timeout=300

clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
